# Generated by Django 2.2.2 on 2019-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
